checks:
  php:
    code_rating: true
    duplication: true

tools:
  external_code_coverage:
    enabled: true
    timeout: 600

filter:
    excluded_paths:
        - tests/bootstrap.php
        - examples/bootstrap.php
