dist: trusty
sudo: false

language: php

matrix:
  include:
    - php: nightly
    - php: 7.2
    - php: 7.1
      dist: precise
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi
  - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi
  - echo memory_limit = -1 >> $INI_FILE
  - composer update

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
after_success:
  # CodeCov
- bash <(curl -s https://codecov.io/bash)
